###############################################################
# DATABASE
###############################################################
# Contains the database imported from Jupyter Notebook
# Do not edit this file


#  1975
#  ====
teams_list_1975 = ['England', 'India', 'New Zealand', 'East Africa', 'Australia', 'Pakistan', 'Sri Lanka',
                   'West Indies']
sig_innings_db_1975 = {('England', 'sig_count'): {1: 1, 2: 2, 3: 3, 4: 1, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('India', 'sig_count'): {1: 1, 2: 1, 3: 1, 4: 0, 5: 0, 6: 0, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('New Zealand', 'sig_count'): {1: 4, 2: 0, 3: 1, 4: 1, 5: 1, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('East Africa', 'sig_count'): {1: 1, 2: 0, 3: 0, 4: 0, 5: 2, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0,
                                                      11: 0},
                       ('Australia', 'sig_count'): {1: 3, 2: 1, 3: 1, 4: 2, 5: 2, 6: 2, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Pakistan', 'sig_count'): {1: 2, 2: 2, 3: 2, 4: 1, 5: 2, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Sri Lanka', 'sig_count'): {1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('West Indies', 'sig_count'): {1: 2, 2: 2, 3: 2, 4: 1, 5: 2, 6: 0, 7: 1, 8: 1, 9: 0, 10: 0,
                                                      11: 0}}
tot_innings_db_1975 = {('England', 'tot_count'): {1: 4, 2: 4, 3: 4, 4: 4, 5: 4, 6: 4, 7: 3, 8: 1, 9: 1, 10: 1, 11: 1},
                       ('India', 'tot_count'): {1: 3, 2: 3, 3: 2, 4: 2, 5: 2, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1, 11: 1},
                       ('New Zealand', 'tot_count'): {1: 4, 2: 4, 3: 4, 4: 4, 5: 4, 6: 4, 7: 4, 8: 3, 9: 2, 10: 2,
                                                      11: 2},
                       ('East Africa', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 3,
                                                      11: 2},
                       ('Australia', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 4, 9: 3, 10: 2, 11: 2},
                       ('Pakistan', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 2, 10: 1, 11: 1},
                       ('Sri Lanka', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 2, 10: 2, 11: 2},
                       ('West Indies', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 4, 5: 4, 6: 3, 7: 3, 8: 2, 9: 2, 10: 2,
                                                      11: 1}}

#  1979
#  ====
teams_list_1979 = ['India', 'West Indies', 'Sri Lanka', 'New Zealand', 'Australia', 'England', 'Canada', 'Pakistan']
sig_innings_db_1979 = {('India', 'sig_count'): {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('West Indies', 'sig_count'): {1: 3, 2: 2, 3: 2, 4: 2, 5: 2, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('Sri Lanka', 'sig_count'): {1: 0, 2: 1, 3: 2, 4: 1, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('New Zealand', 'sig_count'): {1: 3, 2: 2, 3: 2, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 0, 10: 0,
                                                      11: 0},
                       ('Australia', 'sig_count'): {1: 1, 2: 1, 3: 1, 4: 0, 5: 1, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('England', 'sig_count'): {1: 3, 2: 1, 3: 0, 4: 4, 5: 0, 6: 0, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Canada', 'sig_count'): {1: 0, 2: 1, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Pakistan', 'sig_count'): {1: 1, 2: 2, 3: 2, 4: 1, 5: 1, 6: 1, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0}}
tot_innings_db_1979 = {('India', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3},
                       ('West Indies', 'tot_count'): {1: 4, 2: 4, 3: 4, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 2, 10: 1,
                                                      11: 1},
                       ('Sri Lanka', 'tot_count'): {1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 1, 9: 1, 10: 1, 11: 1},
                       ('New Zealand', 'tot_count'): {1: 4, 2: 4, 3: 4, 4: 3, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2,
                                                      11: 2},
                       ('Australia', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2, 11: 2},
                       ('England', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 4, 6: 4, 7: 3, 8: 3, 9: 3, 10: 3, 11: 2},
                       ('Canada', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 2},
                       ('Pakistan', 'tot_count'): {1: 4, 2: 4, 3: 4, 4: 4, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 2, 11: 2}}

#  1983
#  ====
teams_list_1983 = ['England', 'New Zealand', 'Pakistan', 'Sri Lanka', 'Zimbabwe', 'Australia', 'India', 'West Indies']
sig_innings_db_1983 = {('England', 'sig_count'): {1: 5, 2: 4, 3: 4, 4: 5, 5: 1, 6: 0, 7: 1, 8: 1, 9: 0, 10: 0, 11: 0},
                       ('New Zealand', 'sig_count'): {1: 1, 2: 2, 3: 3, 4: 1, 5: 0, 6: 4, 7: 1, 8: 1, 9: 0, 10: 2,
                                                      11: 0},
                       ('Pakistan', 'sig_count'): {1: 4, 2: 1, 3: 1, 4: 5, 5: 4, 6: 0, 7: 2, 8: 1, 9: 1, 10: 0, 11: 0},
                       ('Sri Lanka', 'sig_count'): {1: 2, 2: 2, 3: 1, 4: 4, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 0, 11: 0},
                       ('Zimbabwe', 'sig_count'): {1: 2, 2: 0, 3: 0, 4: 0, 5: 2, 6: 2, 7: 3, 8: 1, 9: 0, 10: 0, 11: 0},
                       ('Australia', 'sig_count'): {1: 2, 2: 2, 3: 3, 4: 2, 5: 3, 6: 1, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('India', 'sig_count'): {1: 0, 2: 2, 3: 3, 4: 5, 5: 3, 6: 1, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('West Indies', 'sig_count'): {1: 3, 2: 2, 3: 4, 4: 4, 5: 0, 6: 1, 7: 0, 8: 0, 9: 1, 10: 0,
                                                      11: 1}}
tot_innings_db_1983 = {('England', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 6, 5: 5, 6: 4, 7: 4, 8: 4, 9: 3, 10: 3, 11: 2},
                       ('New Zealand', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 5, 10: 5,
                                                      11: 4},
                       ('Pakistan', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 6, 7: 6, 8: 5, 9: 5, 10: 4, 11: 1},
                       ('Sri Lanka', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 6, 10: 5, 11: 5},
                       ('Zimbabwe', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 4, 11: 4},
                       ('Australia', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 3, 11: 3},
                       ('India', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 8, 7: 7, 8: 6, 9: 6, 10: 6, 11: 4},
                       ('West Indies', 'tot_count'): {1: 8, 2: 8, 3: 7, 4: 7, 5: 5, 6: 4, 7: 4, 8: 4, 9: 4, 10: 4,
                                                      11: 3}}

#  1987
#  ====
teams_list_1987 = ['Pakistan', 'Sri Lanka', 'West Indies', 'England', 'Australia', 'India', 'New Zealand', 'Zimbabwe']
sig_innings_db_1987 = {('Pakistan', 'sig_count'): {1: 5, 2: 2, 3: 3, 4: 4, 5: 3, 6: 1, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Sri Lanka', 'sig_count'): {1: 0, 2: 2, 3: 1, 4: 2, 5: 4, 6: 2, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('West Indies', 'sig_count'): {1: 2, 2: 2, 3: 3, 4: 4, 5: 2, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('England', 'sig_count'): {1: 6, 2: 2, 3: 5, 4: 6, 5: 6, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Australia', 'sig_count'): {1: 8, 2: 4, 3: 7, 4: 2, 5: 4, 6: 3, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('India', 'sig_count'): {1: 4, 2: 5, 3: 5, 4: 4, 5: 1, 6: 2, 7: 1, 8: 0, 9: 1, 10: 0, 11: 0},
                       ('New Zealand', 'sig_count'): {1: 5, 2: 3, 3: 3, 4: 2, 5: 3, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('Zimbabwe', 'sig_count'): {1: 1, 2: 2, 3: 3, 4: 3, 5: 2, 6: 1, 7: 0, 8: 0, 9: 1, 10: 0, 11: 0}}
tot_innings_db_1987 = {('Pakistan', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 6, 7: 6, 8: 6, 9: 5, 10: 3, 11: 3},
                       ('Sri Lanka', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 5, 10: 4, 11: 1},
                       ('West Indies', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 5, 10: 3,
                                                      11: 2},
                       ('England', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 7, 6: 7, 7: 6, 8: 5, 9: 4, 10: 4, 11: 2},
                       ('Australia', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 8, 7: 7, 8: 4, 9: 4, 10: 4, 11: 1},
                       ('India', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 6, 5: 5, 6: 4, 7: 4, 8: 4, 9: 3, 10: 2, 11: 2},
                       ('New Zealand', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 4,
                                                      11: 2},
                       ('Zimbabwe', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 4, 10: 3, 11: 3}}

#  1992
#  ====
teams_list_1992 = ['New Zealand', 'Australia', 'England', 'India', 'Zimbabwe', 'Sri Lanka', 'Pakistan', 'West Indies',
                   'South Africa']
sig_innings_db_1992 = {
    ('New Zealand', 'sig_count'): {1: 6, 2: 1, 3: 5, 4: 5, 5: 3, 6: 0, 7: 0, 8: 0, 9: 1, 10: 0, 11: 0},
    ('Australia', 'sig_count'): {1: 4, 2: 4, 3: 2, 4: 2, 5: 2, 6: 1, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
    ('England', 'sig_count'): {1: 5, 2: 2, 3: 4, 4: 4, 5: 3, 6: 2, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
    ('India', 'sig_count'): {1: 3, 2: 2, 3: 5, 4: 3, 5: 3, 6: 2, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Zimbabwe', 'sig_count'): {1: 3, 2: 1, 3: 0, 4: 2, 5: 2, 6: 2, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Sri Lanka', 'sig_count'): {1: 3, 2: 4, 3: 0, 4: 3, 5: 3, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Pakistan', 'sig_count'): {1: 3, 2: 5, 3: 3, 4: 8, 5: 2, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('West Indies', 'sig_count'): {1: 4, 2: 5, 3: 2, 4: 1, 5: 4, 6: 1, 7: 1, 8: 1, 9: 0, 10: 0, 11: 0},
    ('South Africa', 'sig_count'): {1: 6, 2: 3, 3: 6, 4: 1, 5: 0, 6: 2, 7: 1, 8: 1, 9: 0, 10: 0, 11: 0}}
tot_innings_db_1992 = {
    ('New Zealand', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 6, 7: 5, 8: 4, 9: 2, 10: 1, 11: 1},
    ('Australia', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 7, 7: 7, 8: 7, 9: 5, 10: 5, 11: 4},
    ('England', 'tot_count'): {1: 10, 2: 10, 3: 10, 4: 9, 5: 8, 6: 8, 7: 7, 8: 7, 9: 5, 10: 4, 11: 3},
    ('India', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 7, 7: 7, 8: 7, 9: 6, 10: 3, 11: 3},
    ('Zimbabwe', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 7, 5: 7, 6: 7, 7: 6, 8: 6, 9: 6, 10: 4, 11: 3},
    ('Sri Lanka', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 7, 7: 7, 8: 7, 9: 6, 10: 4, 11: 3},
    ('Pakistan', 'tot_count'): {1: 10, 2: 10, 3: 10, 4: 10, 5: 9, 6: 8, 7: 7, 8: 6, 9: 4, 10: 4, 11: 2},
    ('West Indies', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 7, 5: 7, 6: 7, 7: 7, 8: 6, 9: 6, 10: 4, 11: 3},
    ('South Africa', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 8, 5: 8, 6: 7, 7: 5, 8: 5, 9: 4, 10: 2, 11: 1}}

#  1996
#  ====
teams_list_1996 = ['Zimbabwe', 'New Zealand', 'England', 'South Africa', 'United Arab Emirates', 'West Indies',
                   'Netherlands', 'Kenya', 'India', 'Sri Lanka', 'Australia', 'Pakistan']
sig_innings_db_1996 = {('Zimbabwe', 'sig_count'): {1: 2, 2: 3, 3: 1, 4: 2, 5: 0, 6: 2, 7: 1, 8: 1, 9: 0, 10: 0, 11: 0},
                       ('New Zealand', 'sig_count'): {1: 2, 2: 2, 3: 5, 4: 3, 5: 3, 6: 2, 7: 2, 8: 0, 9: 1, 10: 0,
                                                      11: 0},
                       ('England', 'sig_count'): {1: 1, 2: 2, 3: 3, 4: 3, 5: 2, 6: 0, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0},
                       ('South Africa', 'sig_count'): {1: 5, 2: 3, 3: 4, 4: 4, 5: 0, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0,
                                                       11: 0},
                       ('United Arab Emirates', 'sig_count'): {1: 1, 2: 1, 3: 1, 4: 0, 5: 1, 6: 1, 7: 0, 8: 0, 9: 1,
                                                               10: 1, 11: 0},
                       ('West Indies', 'sig_count'): {1: 3, 2: 2, 3: 4, 4: 3, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('Netherlands', 'sig_count'): {1: 0, 2: 2, 3: 2, 4: 2, 5: 3, 6: 1, 7: 1, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('Kenya', 'sig_count'): {1: 2, 2: 0, 3: 2, 4: 1, 5: 2, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('India', 'sig_count'): {1: 3, 2: 6, 3: 0, 4: 2, 5: 3, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Sri Lanka', 'sig_count'): {1: 3, 2: 0, 3: 4, 4: 5, 5: 3, 6: 2, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Australia', 'sig_count'): {1: 4, 2: 4, 3: 3, 4: 2, 5: 3, 6: 2, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Pakistan', 'sig_count'): {1: 4, 2: 5, 3: 3, 4: 2, 5: 2, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0}}
tot_innings_db_1996 = {('Zimbabwe', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 4, 10: 3, 11: 3},
                       ('New Zealand', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 7, 7: 7, 8: 7, 9: 6, 10: 6,
                                                      11: 2},
                       ('England', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 5, 7: 4, 8: 4, 9: 4, 10: 4, 11: 3},
                       ('South Africa', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 5, 6: 4, 7: 4, 8: 2, 9: 2, 10: 2,
                                                       11: 2},
                       ('United Arab Emirates', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 4, 7: 4, 8: 4, 9: 4,
                                                               10: 4, 11: 3},
                       ('West Indies', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 4, 10: 4,
                                                      11: 3},
                       ('Netherlands', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 3, 10: 2,
                                                      11: 1},
                       ('Kenya', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 4, 10: 2, 11: 2},
                       ('India', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 5, 7: 5, 8: 3, 9: 3, 10: 3, 11: 1},
                       ('Sri Lanka', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 5, 7: 3, 8: 1, 9: 1, 10: 1, 11: 1},
                       ('Australia', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 6, 6: 6, 7: 5, 8: 5, 9: 4, 10: 1, 11: 1},
                       ('Pakistan', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 5, 5: 4, 6: 3, 7: 3, 8: 2, 9: 1, 10: 1, 11: 1}}

#  1999
#  ====
teams_list_1999 = ['Sri Lanka', 'England', 'India', 'South Africa', 'Kenya', 'Zimbabwe', 'Scotland', 'Australia',
                   'Pakistan', 'West Indies', 'Bangladesh', 'New Zealand']
sig_innings_db_1999 = {('Sri Lanka', 'sig_count'): {1: 1, 2: 1, 3: 2, 4: 1, 5: 2, 6: 3, 7: 3, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('England', 'sig_count'): {1: 3, 2: 1, 3: 2, 4: 2, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('India', 'sig_count'): {1: 4, 2: 2, 3: 5, 4: 3, 5: 2, 6: 3, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('South Africa', 'sig_count'): {1: 2, 2: 5, 3: 2, 4: 3, 5: 5, 6: 3, 7: 3, 8: 3, 9: 2, 10: 0,
                                                       11: 0},
                       ('Kenya', 'sig_count'): {1: 1, 2: 3, 3: 1, 4: 1, 5: 0, 6: 2, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Zimbabwe', 'sig_count'): {1: 4, 2: 3, 3: 3, 4: 0, 5: 4, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Scotland', 'sig_count'): {1: 0, 2: 0, 3: 0, 4: 0, 5: 1, 6: 3, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0},
                       ('Australia', 'sig_count'): {1: 3, 2: 6, 3: 5, 4: 2, 5: 6, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Pakistan', 'sig_count'): {1: 3, 2: 2, 3: 3, 4: 2, 5: 3, 6: 2, 7: 5, 8: 3, 9: 0, 10: 0, 11: 0},
                       ('West Indies', 'sig_count'): {1: 1, 2: 4, 3: 1, 4: 1, 5: 1, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('Bangladesh', 'sig_count'): {1: 1, 2: 2, 3: 1, 4: 0, 5: 0, 6: 3, 7: 1, 8: 0, 9: 0, 10: 0,
                                                     11: 0},
                       ('New Zealand', 'sig_count'): {1: 3, 2: 0, 3: 1, 4: 4, 5: 5, 6: 2, 7: 0, 8: 2, 9: 0, 10: 0,
                                                      11: 0}}
tot_innings_db_1999 = {('Sri Lanka', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 4, 10: 4, 11: 3},
                       ('England', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 4, 5: 3, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2, 11: 2},
                       ('India', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 7, 6: 7, 7: 7, 8: 5, 9: 3, 10: 3, 11: 2},
                       ('South Africa', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 8, 8: 7, 9: 5, 10: 3,
                                                       11: 3},
                       ('Kenya', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 4, 10: 2, 11: 2},
                       ('Zimbabwe', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 8, 7: 8, 8: 7, 9: 5, 10: 5, 11: 4},
                       ('Scotland', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 4, 11: 4},
                       ('Australia', 'tot_count'): {1: 10, 2: 10, 3: 10, 4: 10, 5: 9, 6: 8, 7: 6, 8: 4, 9: 3, 10: 3,
                                                    11: 2},
                       ('Pakistan', 'tot_count'): {1: 10, 2: 10, 3: 10, 4: 9, 5: 9, 6: 9, 7: 9, 8: 9, 9: 8, 10: 7,
                                                   11: 4},
                       ('West Indies', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 4, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2,
                                                      11: 2},
                       ('Bangladesh', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 4,
                                                     11: 4},
                       ('New Zealand', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 6, 8: 4, 9: 4, 10: 3,
                                                      11: 1}}

#  2003
#  ====
teams_list_2003 = ['West Indies', 'South Africa', 'Zimbabwe', 'Namibia', 'Sri Lanka', 'New Zealand', 'Australia',
                   'Pakistan', 'Canada', 'Bangladesh', 'Kenya', 'India', 'Netherlands', 'England']
sig_innings_db_2003 = {
    ('West Indies', 'sig_count'): {1: 2, 2: 2, 3: 3, 4: 3, 5: 2, 6: 3, 7: 2, 8: 1, 9: 0, 10: 0, 11: 0},
    ('South Africa', 'sig_count'): {1: 4, 2: 5, 3: 0, 4: 0, 5: 1, 6: 2, 7: 1, 8: 1, 9: 0, 10: 0, 11: 0},
    ('Zimbabwe', 'sig_count'): {1: 2, 2: 0, 3: 4, 4: 4, 5: 2, 6: 2, 7: 1, 8: 2, 9: 0, 10: 0, 11: 0},
    ('Namibia', 'sig_count'): {1: 1, 2: 2, 3: 1, 4: 2, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Sri Lanka', 'sig_count'): {1: 3, 2: 3, 3: 3, 4: 1, 5: 3, 6: 3, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('New Zealand', 'sig_count'): {1: 1, 2: 5, 3: 3, 4: 3, 5: 5, 6: 1, 7: 1, 8: 1, 9: 1, 10: 0, 11: 0},
    ('Australia', 'sig_count'): {1: 5, 2: 4, 3: 5, 4: 7, 5: 3, 6: 4, 7: 1, 8: 0, 9: 1, 10: 1, 11: 0},
    ('Pakistan', 'sig_count'): {1: 2, 2: 1, 3: 2, 4: 0, 5: 2, 6: 1, 7: 0, 8: 1, 9: 1, 10: 0, 11: 1},
    ('Canada', 'sig_count'): {1: 1, 2: 3, 3: 0, 4: 2, 5: 1, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Bangladesh', 'sig_count'): {1: 0, 2: 1, 3: 1, 4: 0, 5: 0, 6: 2, 7: 1, 8: 0, 9: 1, 10: 0, 11: 0},
    ('Kenya', 'sig_count'): {1: 2, 2: 5, 3: 2, 4: 1, 5: 4, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('India', 'sig_count'): {1: 4, 2: 8, 3: 4, 4: 2, 5: 6, 6: 3, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Netherlands', 'sig_count'): {1: 1, 2: 1, 3: 1, 4: 1, 5: 0, 6: 2, 7: 0, 8: 0, 9: 1, 10: 0, 11: 0},
    ('England', 'sig_count'): {1: 2, 2: 2, 3: 2, 4: 1, 5: 3, 6: 1, 7: 2, 8: 1, 9: 0, 10: 0, 11: 0}}
tot_innings_db_2003 = {
    ('West Indies', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 5, 7: 5, 8: 4, 9: 4, 10: 3, 11: 3},
    ('South Africa', 'tot_count'): {1: 6, 2: 6, 3: 4, 4: 4, 5: 4, 6: 4, 7: 4, 8: 4, 9: 2, 10: 2, 11: 1},
    ('Zimbabwe', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 6, 6: 6, 7: 6, 8: 6, 9: 6, 10: 4, 11: 4},
    ('Namibia', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 5, 10: 5, 11: 5},
    ('Sri Lanka', 'tot_count'): {1: 10, 2: 10, 3: 9, 4: 8, 5: 8, 6: 8, 7: 8, 8: 7, 9: 6, 10: 4, 11: 3},
    ('New Zealand', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 7, 5: 7, 6: 6, 7: 5, 8: 4, 9: 4, 10: 3, 11: 3},
    ('Australia', 'tot_count'): {1: 11, 2: 11, 3: 11, 4: 10, 5: 8, 6: 7, 7: 7, 8: 5, 9: 4, 10: 3, 11: 1},
    ('Pakistan', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 4, 11: 4},
    ('Canada', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 5, 10: 5, 11: 5},
    ('Bangladesh', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 5, 6: 5, 7: 5, 8: 5, 9: 5, 10: 4, 11: 4},
    ('Kenya', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 8, 8: 8, 9: 6, 10: 5, 11: 4},
    ('India', 'tot_count'): {1: 11, 2: 11, 3: 11, 4: 11, 5: 10, 6: 9, 7: 6, 8: 6, 9: 5, 10: 4, 11: 3},
    ('Netherlands', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 5, 10: 5, 11: 5},
    ('England', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 4, 8: 4, 9: 4, 10: 4, 11: 2}}

#  2007
#  ====
teams_list_2007 = ['West Indies', 'Pakistan', 'Australia', 'Scotland', 'Sri Lanka', 'Bermuda', 'Ireland', 'Zimbabwe',
                   'England', 'New Zealand', 'South Africa', 'Netherlands', 'India', 'Bangladesh', 'Canada', 'Kenya']
sig_innings_db_2007 = {
    ('West Indies', 'sig_count'): {1: 3, 2: 2, 3: 4, 4: 3, 5: 7, 6: 3, 7: 1, 8: 1, 9: 0, 10: 1, 11: 0},
    ('Pakistan', 'sig_count'): {1: 0, 2: 1, 3: 0, 4: 2, 5: 1, 6: 1, 7: 0, 8: 0, 9: 1, 10: 0, 11: 0},
    ('Australia', 'sig_count'): {1: 6, 2: 9, 3: 6, 4: 5, 5: 3, 6: 0, 7: 2, 8: 1, 9: 0, 10: 0, 11: 0},
    ('Scotland', 'sig_count'): {1: 0, 2: 0, 3: 1, 4: 0, 5: 0, 6: 1, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Sri Lanka', 'sig_count'): {1: 4, 2: 4, 3: 4, 4: 7, 5: 4, 6: 4, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Bermuda', 'sig_count'): {1: 0, 2: 0, 3: 0, 4: 1, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Ireland', 'sig_count'): {1: 3, 2: 2, 3: 0, 4: 3, 5: 3, 6: 1, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0},
    ('Zimbabwe', 'sig_count'): {1: 0, 2: 1, 3: 0, 4: 1, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('England', 'sig_count'): {1: 3, 2: 3, 3: 3, 4: 6, 5: 4, 6: 1, 7: 1, 8: 3, 9: 0, 10: 0, 11: 0},
    ('New Zealand', 'sig_count'): {1: 4, 2: 5, 3: 3, 4: 6, 5: 3, 6: 3, 7: 2, 8: 0, 9: 2, 10: 0, 11: 1},
    ('South Africa', 'sig_count'): {1: 4, 2: 4, 3: 5, 4: 5, 5: 4, 6: 0, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Netherlands', 'sig_count'): {1: 1, 2: 0, 3: 0, 4: 2, 5: 0, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('India', 'sig_count'): {1: 1, 2: 1, 3: 2, 4: 0, 5: 2, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Bangladesh', 'sig_count'): {1: 1, 2: 1, 3: 1, 4: 0, 5: 4, 6: 2, 7: 2, 8: 1, 9: 1, 10: 0, 11: 0},
    ('Canada', 'sig_count'): {1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0},
    ('Kenya', 'sig_count'): {1: 0, 2: 0, 3: 1, 4: 1, 5: 0, 6: 0, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0}}
tot_innings_db_2007 = {
    ('West Indies', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 8, 6: 8, 7: 7, 8: 6, 9: 6, 10: 6, 11: 6},
    ('Pakistan', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 3},
    ('Australia', 'tot_count'): {1: 10, 2: 10, 3: 9, 4: 8, 5: 8, 6: 5, 7: 4, 8: 3, 9: 0, 10: 0, 11: 0},
    ('Scotland', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 2, 11: 1},
    ('Sri Lanka', 'tot_count'): {1: 11, 2: 11, 3: 11, 4: 11, 5: 10, 6: 10, 7: 8, 8: 6, 9: 4, 10: 4, 11: 3},
    ('Bermuda', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 3, 9: 3, 10: 3, 11: 2},
    ('Ireland', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 9, 7: 9, 8: 9, 9: 9, 10: 7, 11: 4},
    ('Zimbabwe', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 2, 9: 2, 10: 2, 11: 2},
    ('England', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 8, 8: 8, 9: 6, 10: 3, 11: 3},
    ('New Zealand', 'tot_count'): {1: 10, 2: 10, 3: 10, 4: 9, 5: 9, 6: 8, 7: 7, 8: 5, 9: 5, 10: 3, 11: 2},
    ('South Africa', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 8, 5: 8, 6: 5, 7: 4, 8: 4, 9: 4, 10: 3, 11: 3},
    ('Netherlands', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2, 11: 1},
    ('India', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 3, 8: 2, 9: 2, 10: 2, 11: 2},
    ('Bangladesh', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 8, 8: 7, 9: 6, 10: 6, 11: 5},
    ('Canada', 'tot_count'): {1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 10: 1, 11: 1},
    ('Kenya', 'tot_count'): {1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 10: 2, 11: 2}}

#  2011
#  ====
teams_list_2011 = ['India', 'Bangladesh', 'Kenya', 'New Zealand', 'Sri Lanka', 'Canada', 'Australia', 'Zimbabwe',
                   'Netherlands', 'England', 'Pakistan', 'West Indies', 'South Africa', 'Ireland']
sig_innings_db_2011 = {('India', 'sig_count'): {1: 5, 2: 5, 3: 6, 4: 4, 5: 3, 6: 2, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Bangladesh', 'sig_count'): {1: 3, 2: 2, 3: 1, 4: 3, 5: 1, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0,
                                                     11: 0},
                       ('Kenya', 'sig_count'): {1: 0, 2: 0, 3: 4, 4: 1, 5: 1, 6: 1, 7: 0, 8: 2, 9: 0, 10: 0, 11: 0},
                       ('New Zealand', 'sig_count'): {1: 4, 2: 2, 3: 2, 4: 5, 5: 1, 6: 2, 7: 1, 8: 1, 9: 1, 10: 0,
                                                      11: 0},
                       ('Sri Lanka', 'sig_count'): {1: 5, 2: 6, 3: 5, 4: 3, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Canada', 'sig_count'): {1: 1, 2: 0, 3: 1, 4: 3, 5: 3, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Australia', 'sig_count'): {1: 3, 2: 5, 3: 1, 4: 3, 5: 0, 6: 1, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Zimbabwe', 'sig_count'): {1: 2, 2: 1, 3: 2, 4: 2, 5: 2, 6: 2, 7: 1, 8: 1, 9: 1, 10: 0, 11: 0},
                       ('Netherlands', 'sig_count'): {1: 0, 2: 2, 3: 2, 4: 2, 5: 1, 6: 1, 7: 0, 8: 1, 9: 0, 10: 0,
                                                      11: 0},
                       ('England', 'sig_count'): {1: 3, 2: 1, 3: 6, 4: 2, 5: 3, 6: 0, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('Pakistan', 'sig_count'): {1: 2, 2: 3, 3: 5, 4: 3, 5: 4, 6: 4, 7: 0, 8: 1, 9: 0, 10: 1, 11: 0},
                       ('West Indies', 'sig_count'): {1: 3, 2: 5, 3: 3, 4: 2, 5: 4, 6: 2, 7: 0, 8: 1, 9: 0, 10: 0,
                                                      11: 0},
                       ('South Africa', 'sig_count'): {1: 4, 2: 2, 3: 4, 4: 4, 5: 3, 6: 2, 7: 1, 8: 0, 9: 0, 10: 0,
                                                       11: 0},
                       ('Ireland', 'sig_count'): {1: 2, 2: 1, 3: 1, 4: 3, 5: 2, 6: 2, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0}}
tot_innings_db_2011 = {('India', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 7, 8: 4, 9: 4, 10: 4, 11: 4},
                       ('Bangladesh', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 5, 10: 5,
                                                     11: 4},
                       ('Kenya', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 5, 11: 5},
                       ('New Zealand', 'tot_count'): {1: 8, 2: 8, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 4,
                                                      11: 3},
                       ('Sri Lanka', 'tot_count'): {1: 8, 2: 8, 3: 7, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 3, 10: 2, 11: 2},
                       ('Canada', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 5, 10: 5, 11: 5},
                       ('Australia', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 4, 7: 4, 8: 4, 9: 1, 10: 1, 11: 1},
                       ('Zimbabwe', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 4, 11: 4},
                       ('Netherlands', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 5,
                                                      11: 5},
                       ('England', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 7, 7: 6, 8: 6, 9: 5, 10: 4, 11: 3},
                       ('Pakistan', 'tot_count'): {1: 8, 2: 8, 3: 7, 4: 7, 5: 7, 6: 6, 7: 6, 8: 6, 9: 4, 10: 3, 11: 3},
                       ('West Indies', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 6, 10: 6,
                                                      11: 5},
                       ('South Africa', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 6, 7: 6, 8: 5, 9: 5, 10: 3,
                                                       11: 2},
                       ('Ireland', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 5, 10: 4, 11: 4}}

#  2015
#  ====
teams_list_2015 = ['New Zealand', 'Sri Lanka', 'Australia', 'England', 'South Africa', 'Zimbabwe', 'India', 'Pakistan',
                   'West Indies', 'Ireland', 'Scotland', 'Bangladesh', 'Afghanistan', 'United Arab Emirates']
sig_innings_db_2015 = {
    ('New Zealand', 'sig_count'): {1: 4, 2: 5, 3: 4, 4: 3, 5: 3, 6: 3, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Sri Lanka', 'sig_count'): {1: 3, 2: 3, 3: 6, 4: 1, 5: 3, 6: 3, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0},
    ('Australia', 'sig_count'): {1: 4, 2: 2, 3: 5, 4: 3, 5: 3, 6: 3, 7: 0, 8: 2, 9: 0, 10: 0, 11: 0},
    ('England', 'sig_count'): {1: 2, 2: 4, 3: 0, 4: 2, 5: 1, 6: 1, 7: 1, 8: 2, 9: 0, 10: 0, 11: 0},
    ('South Africa', 'sig_count'): {1: 1, 2: 3, 3: 5, 4: 4, 5: 6, 6: 3, 7: 1, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Zimbabwe', 'sig_count'): {1: 2, 2: 1, 3: 1, 4: 4, 5: 5, 6: 2, 7: 1, 8: 1, 9: 0, 10: 0, 11: 0},
    ('India', 'sig_count'): {1: 4, 2: 5, 3: 6, 4: 3, 5: 2, 6: 3, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Pakistan', 'sig_count'): {1: 3, 2: 2, 3: 4, 4: 6, 5: 2, 6: 1, 7: 1, 8: 1, 9: 0, 10: 0, 11: 0},
    ('West Indies', 'sig_count'): {1: 1, 2: 3, 3: 2, 4: 2, 5: 1, 6: 3, 7: 2, 8: 1, 9: 3, 10: 0, 11: 0},
    ('Ireland', 'sig_count'): {1: 3, 2: 2, 3: 3, 4: 3, 5: 2, 6: 1, 7: 2, 8: 0, 9: 0, 10: 0, 11: 0},
    ('Scotland', 'sig_count'): {1: 2, 2: 0, 3: 1, 4: 3, 5: 1, 6: 1, 7: 0, 8: 0, 9: 1, 10: 0, 11: 0},
    ('Bangladesh', 'sig_count'): {1: 1, 2: 0, 3: 3, 4: 3, 5: 2, 6: 4, 7: 2, 8: 2, 9: 0, 10: 0, 11: 0},
    ('Afghanistan', 'sig_count'): {1: 1, 2: 0, 3: 2, 4: 2, 5: 2, 6: 2, 7: 0, 8: 1, 9: 0, 10: 0, 11: 0},
    ('United Arab Emirates', 'sig_count'): {1: 1, 2: 0, 3: 1, 4: 4, 5: 2, 6: 4, 7: 1, 8: 3, 9: 0, 10: 0, 11: 0}}
tot_innings_db_2015 = {
    ('New Zealand', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 8, 6: 8, 7: 7, 8: 6, 9: 4, 10: 2, 11: 2},
    ('Sri Lanka', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 4, 10: 4, 11: 4},
    ('Australia', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 6, 7: 5, 8: 4, 9: 4, 10: 3, 11: 2},
    ('England', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 4, 10: 4, 11: 3},
    ('South Africa', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 7, 5: 7, 6: 7, 7: 5, 8: 3, 9: 2, 10: 2, 11: 2},
    ('Zimbabwe', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 5, 11: 5},
    ('India', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 7, 5: 6, 6: 6, 7: 5, 8: 5, 9: 3, 10: 1, 11: 1},
    ('Pakistan', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 6, 7: 6, 8: 6, 9: 5, 10: 4, 11: 4},
    ('West Indies', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 4, 10: 3, 11: 3},
    ('Ireland', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 5, 10: 5, 11: 3},
    ('Scotland', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 6, 10: 6, 11: 5},
    ('Bangladesh', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 5, 8: 5, 9: 5, 10: 3, 11: 3},
    ('Afghanistan', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 6, 10: 5, 11: 5},
    ('United Arab Emirates', 'tot_count'): {1: 6, 2: 6, 3: 6, 4: 6, 5: 6, 6: 6, 7: 6, 8: 6, 9: 6, 10: 5, 11: 3}}

#  2019
#  ====
teams_list_2019 = ['England', 'South Africa', 'Pakistan', 'West Indies', 'Sri Lanka', 'New Zealand', 'Afghanistan',
                   'Australia', 'Bangladesh', 'India', 'Zimbabwe', 'Netherlands', 'Ireland']
sig_innings_db_2019 = {('England', 'sig_count'): {1: 6, 2: 7, 3: 7, 4: 4, 5: 6, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('South Africa', 'sig_count'): {1: 3, 2: 6, 3: 5, 4: 3, 5: 5, 6: 3, 7: 2, 8: 1, 9: 1, 10: 0,
                                                       11: 0},
                       ('Pakistan', 'sig_count'): {1: 3, 2: 5, 3: 7, 4: 2, 5: 4, 6: 1, 7: 2, 8: 1, 9: 1, 10: 0, 11: 0},
                       ('West Indies', 'sig_count'): {1: 4, 2: 3, 3: 3, 4: 5, 5: 4, 6: 3, 7: 0, 8: 1, 9: 0, 10: 0,
                                                      11: 0},
                       ('Sri Lanka', 'sig_count'): {1: 2, 2: 5, 3: 3, 4: 3, 5: 2, 6: 2, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0},
                       ('New Zealand', 'sig_count'): {1: 2, 2: 2, 3: 8, 4: 5, 5: 2, 6: 1, 7: 2, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('Afghanistan', 'sig_count'): {1: 3, 2: 5, 3: 4, 4: 2, 5: 3, 6: 3, 7: 3, 8: 0, 9: 1, 10: 0,
                                                      11: 0},
                       ('Australia', 'sig_count'): {1: 6, 2: 5, 3: 4, 4: 4, 5: 2, 6: 0, 7: 5, 8: 1, 9: 0, 10: 0, 11: 0},
                       ('Bangladesh', 'sig_count'): {1: 2, 2: 3, 3: 7, 4: 4, 5: 2, 6: 2, 7: 2, 8: 1, 9: 0, 10: 0,
                                                     11: 0},
                       ('India', 'sig_count'): {1: 6, 2: 6, 3: 5, 4: 3, 5: 2, 6: 5, 7: 2, 8: 1, 9: 0, 10: 0, 11: 0},
                       ('Zimbabwe', 'sig_count'): {1: 0, 2: 0, 3: 3, 4: 2, 5: 2, 6: 2, 7: 1, 8: 1, 9: 2, 10: 0, 11: 0},
                       ('Netherlands', 'sig_count'): {1: 1, 2: 2, 3: 1, 4: 0, 5: 1, 6: 1, 7: 1, 8: 0, 9: 0, 10: 0,
                                                      11: 0},
                       ('Ireland', 'sig_count'): {1: 3, 2: 2, 3: 1, 4: 1, 5: 1, 6: 1, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0}}
tot_innings_db_2019 = {
    ('England', 'tot_count'): {1: 11, 2: 11, 3: 11, 4: 11, 5: 9, 6: 9, 7: 9, 8: 9, 9: 7, 10: 6, 11: 4},
    ('South Africa', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 6, 5: 6, 6: 6, 7: 6, 8: 5, 9: 4, 10: 4, 11: 2},
    ('Pakistan', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 8, 7: 7, 8: 7, 9: 6, 10: 4, 11: 3},
    ('West Indies', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 7, 7: 7, 8: 7, 9: 6, 10: 5, 11: 5},
    ('Sri Lanka', 'tot_count'): {1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 7, 7: 7, 8: 7, 9: 6, 10: 5, 11: 5},
    ('New Zealand', 'tot_count'): {1: 10, 2: 10, 3: 9, 4: 9, 5: 9, 6: 8, 7: 8, 8: 8, 9: 6, 10: 5, 11: 2},
    ('Afghanistan', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 9, 7: 9, 8: 9, 9: 9, 10: 9, 11: 8},
    ('Australia', 'tot_count'): {1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 9, 7: 9, 8: 8, 9: 8, 10: 6, 11: 6},
    ('Bangladesh', 'tot_count'): {1: 8, 2: 8, 3: 8, 4: 8, 5: 8, 6: 7, 7: 7, 8: 7, 9: 5, 10: 4, 11: 4},
    ('India', 'tot_count'): {1: 9, 2: 9, 3: 9, 4: 9, 5: 9, 6: 8, 7: 7, 8: 4, 9: 4, 10: 3, 11: 1},
    ('Zimbabwe', 'tot_count'): {1: 5, 2: 5, 3: 5, 4: 5, 5: 5, 6: 5, 7: 5, 8: 5, 9: 4, 10: 4, 11: 3},
    ('Netherlands', 'tot_count'): {1: 2, 2: 2, 3: 2, 4: 2, 5: 2, 6: 1, 7: 1, 8: 1, 9: 1, 10: 0, 11: 0},
    ('Ireland', 'tot_count'): {1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3, 7: 2, 8: 2, 9: 1, 10: 1, 11: 1}}

# Creating the Mega Database

years = [1975, 1979, 1983, 1987, 1992, 1996, 1999, 2003, 2007, 2011, 2015, 2019]
sig_1 = [sig_innings_db_1975, sig_innings_db_1979,
         sig_innings_db_1983, sig_innings_db_1987,
         sig_innings_db_1992, sig_innings_db_1996,
         sig_innings_db_1999, sig_innings_db_2003,
         sig_innings_db_2007, sig_innings_db_2011,
         sig_innings_db_2015, sig_innings_db_2019
         ]

tot_1 = [tot_innings_db_1975, tot_innings_db_1979,
         tot_innings_db_1983, tot_innings_db_1987,
         tot_innings_db_1992, tot_innings_db_1996,
         tot_innings_db_1999, tot_innings_db_2003,
         tot_innings_db_2007, tot_innings_db_2011,
         tot_innings_db_2015, tot_innings_db_2019
         ]

sig_mega_db = dict(zip(years, sig_1))
tot_mega_db = dict(zip(years, tot_1))

# Batting Talents with good average score for their respective countries

talent_list = {'Afghanistan': ['Rahmat Shah'],
               'Australia': ['Michael Clarke', 'Donald Bradman', 'Allan Border', 'Steve Waugh', 'Ricky Ponting',
                             'Michael Bevan', 'Michael Hussey', 'Steven Smith'],
               'Bangladesh': ['Tamim Iqbal', 'Shakib Al Hasan'],
               'Bermuda': ['David Hemp'],
               'Canada': ['Ashish Bagai'],
               'East Africa': ['Mehmood Quaraishy'],
               'England': ['Joe Root', 'Ian Botham', 'Jack Hobbs', 'Allan Lamb', 'Nick Knight', 'Kevin Pietersen'],
               'India': ['Sachin Tendulkar', 'Virat Kohli'],
               'Ireland': ['Ed Joyce', 'PR Stirling', 'William Porterfield'],
               'Kenya': ['Steve Tikolo'],
               'Namibia': ['Craig Williams', 'JP Kotze'],
               'Netherlands': ['Tom Cooper', 'Ryan ten Doeschate'],
               'New Zealand': ['Nathan Astle', 'Martin Crowe', 'Roger Twose', 'Glenn Turner', 'Kane Williamson',
                               'Ross Taylor', 'Bert Sutcliffe'],
               'Pakistan': ['Inzamam-ul-Haq', 'Mohammad Yousuf', 'Saeed Anwar', 'Javed Miandad', 'Younis Khan',
                            'Misbah-ul-Haq'],
               'Scotland': ['Calum MacLeod', 'Kyle Coetzer'],
               'South Africa': ['AB de Villiers', 'Jacques Kallis', 'Gary Kirsten', 'Hashim Amla'],
               'Sri Lanka': ['Kumar Sangakkara', 'Arjuna Ranatunga', 'Angelo Mathews'],
               'United Arab Emirates': ['Shaiman Anwar', 'Rameez Shahzad', 'Khurram Khan'],
               'West Indies': ['Vivian Richards', 'Brian Lara', 'Shivnarine Chanderpaul'],
               'Zimbabwe': ['Brendan Taylor', 'Andy Flower', 'Sean Williams']}
